### ISSUE TITLE
Does not build - type issue

### ISSUE THREAD

**Issue by quicklisp** [Lovesan/bike#2]
I get this: 
```
; caught WARNING:
;   The fourth argument of type (UNSIGNED-BYTE 62) cannot be used as a keyword.
; 
; caught WARNING:
;   The sixth argument of type (UNSIGNED-BYTE 62) cannot be used as a keyword.
```

Full log here: http://report.quicklisp.org/2020-02-24/failure-report/bike.html#bike

**Comment by Lovesan** [comment]
Investigating now

**Comment by Lovesan** [comment]
https://github.com/Lovesan/bike/commit/6d683bc2346b7c5a6862c9b04180ce67e3d9f5b1 should fix this

**Comment by Lovesan** [comment]
Seems like the latest SBCL improved argument type deduction a bit.

**Comment by Lovesan** [comment]
Ok, it seems like fixed. I don't see the warning in ql reports anymore. I'm closing the issue.
