### ISSUE TITLE
Exception handling on Windows should be saner now

### ISSUE THREAD

**Issue by luismbo** [Lovesan/bike#7]
I've just come across your README discussion about SBCL's exception handling on Windows. That [has recently been fixed in SBCL](https://github.com/sbcl/sbcl/commit/50085a82c7bd6dfb91599f236e3d002f49ebec72), so you can update the README if you wish.

**Comment by Lovesan** [comment]
That's pretty cool! I'll definitely mention it

**Comment by Lovesan** [comment]
Done
